// Ported verbatim from the reference Android app's res/raw/hello.txt (one greeting per line,
// "hello" in a long list of languages/scripts, plus two easter-egg entries) - there it's shown
// as "$greeting," atop the nav drawer, re-picked every time the drawer opens. Here it's shown
// atop Settings for the same reason: purely a friendly, ever-changing touch, re-picked every
// time the panel opens.
export const GREETINGS: readonly string[] = [
  "Akkam",
  "Håfa adai",
  "Kablaaw",
  "Sannu",
  "Olá",
  "Салом",
  "Muraho",
  "வணக்கம்",
  "Aloha",
  "Niltze",
  "שלום",
  "བཀྲ་ཤིས་བདེ་ལེགས",
  "Hei",
  "Napaykullayki",
  "Sveiki",
  "Nnọọ",
  "Sampurasun",
  "ਸਤਿ ਸ਼੍ਰੀ ਅਕਾਲ",
  "مرحبا",
  "Здравствуйте",
  "Bok",
  "Hallo",
  "Dobrý deň",
  "Ia orana",
  "Sak pase",
  "Hola",
  "Tungjatjeta",
  "ᎣᏏᏲ",
  "שלום עליכם",
  "ສະບາຍດີ",
  "Hallo",
  "Bawo ni",
  "Tere",
  "ستړی مه شی",
  "Bula",
  "Om Swastiastu",
  "Yá'át'ééh",
  "Kaixo",
  "ᜃᜓᜋᜓᜐ᜔ᜆ",
  "こんにちは",
  "Halló",
  "Bongu",
  "سلام",
  "Nangi def",
  "Cześć",
  "Mhoro",
  "Hej",
  "Salut",
  "Xin chào",
  "Talofa",
  "Bonjour",
  "ආයුබෝවන්",
  "Malo e lelei",
  "নমস্কার",
  "سڵاو",
  "Γειά σου",
  "Molo",
  "Nabad",
  "ᐊᐃᖓᐃ",
  "ياخشىمۇسىز",
  "Jambo",
  "你好",
  "ሰላም",
  "Hallo",
  "Сайн байна уу",
  "నమస్కారం",
  "Szia",
  "你好",
  "Здравейте",
  "Kia ora",
  "Merhaba",
  "Sawubona",
  "नमस्ते",
  "Dumela",
  "Helo",
  "Привіт",
  "Demat",
  "Բարև",
  "မင်္ဂလာပါ",
  "Aluu",
  "કેમ છો",
  "안녕하세요",
  "ជំរាបសួរ",
  "Mba'éichapa",
  "Ciao",
  "Сәлем",
  "Salama",
  "السلام علیکم",
  "สวัสดี",
  "Kamisaraki",
  "Saluton",
  "Cooter",
  "Minecraft?!",
  "Moni",
  "Ahoj",
  "Nyob zoo",
  "გამარჯობა",
  "Živjo",
  "Dia dhuit",
  "Moien",
];

export function randomGreeting(): string {
  return GREETINGS[Math.floor(Math.random() * GREETINGS.length)];
}
